name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      
    - name: Build
    - run:
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install pyinstaller
        pyinstaller neoreset.py \
        --onefile \
        --add-data assets:assets \
        --add-data VERSION:. \
        --add-data README.md:. \
        --add-data LICENSE:. \
        --add-data neoreset.json:. \
        --add-binary bin:bin \
        --add-binary lib:lib \
        --hidden-import=pynput.keyboard._xorg \
        --hidden-import=pynput.mouse._xorg

    - uses: actions/upload-artifact@v2
      with:
        name: linux
        path: dist/neoreset
